# Generated by Django 2.2.7 on 2019-11-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monsterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterName', models.CharField(max_length=32)),
                ('hp', models.CharField(max_length=3)),
                ('ac', models.CharField(max_length=3)),
                ('special', models.CharField(max_length=32)),
            ],
        ),
    ]
