# Generated by Django 2.2.7 on 2019-12-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0002_monstertable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monstertable',
            old_name='ac',
            new_name='monsterAC',
        ),
        migrations.RenameField(
            model_name='monstertable',
            old_name='hp',
            new_name='monsterHP',
        ),
    ]
