# Generated by Django 2.2.7 on 2019-12-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0003_auto_20191204_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstertable',
            name='monsterCR',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
